[rutas]
certificate = '12069487-1.pfx'
documentos_originales = '/home/atorres/firmador-pfx/in'
documentos_firmados = '/home/atorres/firmador-pfx/out'
; **** Ejemplo para windows ****
; documentos_originales = 'C:\Users\Gonzalo\Firma masiva\pdfs\in'
; documentos_firmados = 'C:\Users\Gonzalo\Firma masiva\pdfs\out'
imagen_firma = '~/firmador-pfx/firma-template.png'

[firma]
; ambos ejes se puedes sobre escribir pasando como parametro.
eje_x = 116
eje_y = 139
ancho = 60
alto = 14
fontSizeNombre = 28
fontSizeFecha = 18

[info]
; Información adicional de la firma
Names = 'Gonzalo Edgardo'
LastNames = 'Torres Fuchslocher'
Location = 'Servicio de Impuestos Internos'
Reason = 'Firma electrónica avanzada'
ContactInfo = 'http://www.sii.cl'
